#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Coordenada; end

class Coordenada
  include ::Thrift::Struct, ::Thrift::Struct_Union
  X = 1
  Y = 2

  FIELDS = {
    X => {:type => ::Thrift::Types::DOUBLE, :name => 'x'},
    Y => {:type => ::Thrift::Types::DOUBLE, :name => 'y'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field x is unset!') unless @x
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field y is unset!') unless @y
  end

  ::Thrift::Struct.generate_accessors self
end

